[project]
name = "marimo-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "altair>=5.5.0",
    "marimo>=0.11.17",
    "plotly>=6.0.0",
    "requests>=2.32.4",
    "scipy>=1.15.1",
    "seaborn>=0.13.2",
    "wigglystuff>=0.1.9",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.9.6",
]
